ALLERGEN_MAP = {
    'milk': ['milk', 'milk powder', 'dairy', 'milks'],
    'milks': ['milk', 'milk powder', 'dairy', 'milks'],
    'eggs': ['egg', 'egg white', 'egg yolk', 'eggs'],
    'egg': ['egg', 'egg white', 'egg yolk', 'eggs'],
    'peanuts': ['peanuts', 'groundnuts', 'peanut', 'peanut butter'],
    'peanut': ['peanuts', 'groundnuts', 'peanut', 'peanut butter'],
    'tree nuts': ['almonds', 'cashews', 'hazelnuts', 'macadamia nuts', 'pecans', 'pistachios', 'walnuts', 'tree nuts'],
    'tree nut': ['almonds', 'cashews', 'hazelnuts', 'macadamia nuts', 'pecans', 'pistachios', 'walnuts', 'tree nuts'],
    'soy': ['soy', 'soybeans', 'soy protein', 'soy lecithin', 'soys'],
    'soys': ['soy', 'soybeans', 'soy protein', 'soy lecithin', 'soys'],
    'wheat': ['wheat', 'wheat flour', 'gluten', 'wheats'],
    'wheats': ['wheat', 'wheat flour', 'gluten', 'wheats'],
    'fish': ['fish', 'fish sauce', 'fishes'],
    'fishes': ['fish', 'fish sauce', 'fishes'],
    'shellfish': ['shrimp', 'crab', 'lobster', 'prawns', 'shellfish'],
    'sesame': ['sesame', 'sesame seeds'],
    'sesames': ['sesame', 'sesame seeds'],
    'corn': ['corn', 'cornstarch'],
    'mustard': ['mustard', 'mustard seeds'],
    'sulfites': ['sulfites', 'sulfur dioxide'],
    'artificial colors': ['artificial colors', 'dye', 'coloring'],
    'caffeine': ['caffeine'],
    'lactose': ['lactose'],
    'casein': ['casein'],
    'pollen': ['pollen', 'grass pollen', 'ragweed pollen'],
    'dust mites': ['dust mites', 'dust'],
    'mold': ['mold', 'mold spores'],
    'pet dander': ['pet dander', 'cat dander', 'dog dander'],
    'latex': ['latex'],
    'bees': ['bees', 'honeybee'],
    'wasps': ['wasps', 'yellow jackets'],
    'nickel': ['nickel'],
    'fragrances': ['fragrances', 'perfumes', 'scents'],
    'antibiotics': ['antibiotics', 'penicillin'],
    'nsaids': ['nsaids', 'ibuprofen', 'aspirin'],
    'sulfa drugs': ['sulfa drugs', 'sulfonamides'],
    'soy sauce': ['soy sauce'],
    'alcohol': ['alcohol'],
    'ginger': ['ginger'],
    'garlic': ['garlic'],
    'turmeric': ['turmeric'],
    'msg': ['msg', 'monosodium glutamate'],
    'asparagus': ['asparagus'],
    'tomatoes': ['tomatoes'],
    'avocado': ['avocado'],
    'bananas': ['bananas'],
    'citrus fruits': ['citrus fruits', 'oranges', 'lemons'],
    'citrus fruit': ['citrus fruit', 'orange', 'lemon'],
    'strawberries': ['strawberries'],
    'apples': ['apples'],
    'peaches': ['peaches'],
    'pineapple': ['pineapple'],
    'coconut': ['coconut'],
    'grapes': ['grapes'],
    'celery': ['celery'],
    'carrots': ['carrots'],
    'onions': ['onions'],
    'onion': ['onions']
}
